/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const AppBaseRouteGuard: typeof import('@/app/components/base/AppBaseRouteGuard.tsx')['AppBaseRouteGuard']
  const AppBaseSvg: typeof import('@/app/components/base/AppBaseSvg.tsx')['AppBaseSvg']
  const AppBaseText: typeof import('@/app/components/base/AppBaseText.tsx')['AppBaseText']
  const AppBaseToast: typeof import('@/app/components/base/AppBaseToast.tsx')['AppBaseToast']
  const AppBaseWrapper: typeof import('@/app/components/base/AppBaseWrapper.tsx')['AppBaseWrapper']
  const AppCommonEntryPoint: typeof import('@/app/components/common/AppCommonEntryPoint.tsx')['AppCommonEntryPoint']
  const createRef: typeof import('react')['createRef']
  const forwardRef: typeof import('react')['forwardRef']
  const getComponentImports: typeof import('../helpers/auto-imports.helper')['getComponentImports']
  const lazy: typeof import('react')['lazy']
  const memo: typeof import('react')['memo']
  const startTransition: typeof import('react')['startTransition']
  const useCallback: typeof import('react')['useCallback']
  const useContext: typeof import('react')['useContext']
  const useDebugValue: typeof import('react')['useDebugValue']
  const useDeferredValue: typeof import('react')['useDeferredValue']
  const useEffect: typeof import('react')['useEffect']
  const useId: typeof import('react')['useId']
  const useImperativeHandle: typeof import('react')['useImperativeHandle']
  const useInsertionEffect: typeof import('react')['useInsertionEffect']
  const useLayoutEffect: typeof import('react')['useLayoutEffect']
  const useMemo: typeof import('react')['useMemo']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useState: typeof import('react')['useState']
  const useSyncExternalStore: typeof import('react')['useSyncExternalStore']
  const useTransition: typeof import('react')['useTransition']
}
